# Generated by Django 4.1 on 2022-08-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('TS', 'Футболка'), ('H', 'Худи'), ('S', 'Рубашка')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'Основной'), ('S', 'Вторичный'), ('D', 'Третичный')], max_length=1),
        ),
    ]
